# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1353, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 70, 101, 91))
        self.pushButton.setStyleSheet("color:rgb(255, 85, 0)")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/todayicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(70, 70))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 180, 101, 81))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 400, 101, 81))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 510, 101, 91))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 620, 101, 91))
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/themes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(190, 50, 1091, 701))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(930, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(460, 50, 51, 31))
        self.label.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(680, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(520, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(750, 51, 141, 31))
        self.comboBox_2.setMouseTracking(False)
        self.comboBox_2.setTabletTracking(False)
        self.comboBox_2.setAcceptDrops(False)
        self.comboBox_2.setAutoFillBackground(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAutoFillBackground(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 110, 1051, 511))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(5)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        self.pushButton_30 = QtWidgets.QPushButton(self.tab)
        self.pushButton_30.setGeometry(QtCore.QRect(780, 632, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.label.raise_()
        self.pushButton_6.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.lineEdit_5.raise_()
        self.tableWidget_6.raise_()
        self.pushButton_30.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(6, -1, 1021, 661))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 1011, 581))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(7)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_26.setGeometry(QtCore.QRect(744, 590, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_31.setGeometry(QtCore.QRect(340, 590, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("\n"
"")
        self.pushButton_31.setObjectName("pushButton_31")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_21.setGeometry(QtCore.QRect(510, 590, 191, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(710, 100, 241, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 110, 291, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setGeometry(QtCore.QRect(710, 170, 241, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setGeometry(QtCore.QRect(710, 260, 241, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        self.comboBox_5.setGeometry(QtCore.QRect(710, 340, 241, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(710, 420, 241, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 570, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(570, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(570, 440, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(570, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(570, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(570, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 220, 471, 281))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget_2.addTab(self.widget, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(550, 420, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_9.setGeometry(QtCore.QRect(710, 260, 241, 31))
        self.comboBox_9.setObjectName("comboBox_9")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(550, 250, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 60, 301, 31))
        self.lineEdit_8.setAutoFillBackground(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(50, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_10.setGeometry(QtCore.QRect(710, 310, 241, 31))
        self.comboBox_10.setAutoFillBackground(True)
        self.comboBox_10.setObjectName("comboBox_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(710, 200, 241, 31))
        self.lineEdit_9.setAutoFillBackground(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(670, 470, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(550, 310, 91, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(550, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(710, 410, 241, 41))
        self.lineEdit_10.setAutoFillBackground(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(550, 360, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_11.setGeometry(QtCore.QRect(710, 360, 241, 31))
        self.comboBox_11.setAutoFillBackground(True)
        self.comboBox_11.setObjectName("comboBox_11")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(560, 50, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setAutoFillBackground(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_11.setGeometry(QtCore.QRect(170, 480, 151, 41))
        self.pushButton_11.setAutoFillBackground(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.textEdit = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit.setGeometry(QtCore.QRect(30, 170, 441, 281))
        self.textEdit.setAutoFillBackground(True)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(180, 130, 301, 31))
        self.lineEdit_11.setAutoFillBackground(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(50, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 501, 651))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(20, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(20, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(20, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(10, 280, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(230, 100, 241, 31))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_13.setGeometry(QtCore.QRect(230, 160, 241, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_14.setGeometry(QtCore.QRect(230, 220, 241, 31))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_15.setGeometry(QtCore.QRect(230, 280, 241, 31))
        self.lineEdit_15.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(180, 450, 121, 51))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(100, 350, 301, 31))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 10, 531, 241))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(60, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_24.setGeometry(QtCore.QRect(230, 100, 241, 31))
        self.lineEdit_24.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_25.setGeometry(QtCore.QRect(230, 50, 241, 31))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(60, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_15.setGeometry(QtCore.QRect(200, 160, 131, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(530, 290, 531, 371))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_30.setGeometry(QtCore.QRect(270, 180, 241, 31))
        self.lineEdit_30.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_28.setGeometry(QtCore.QRect(270, 120, 241, 31))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        self.label_41.setGeometry(QtCore.QRect(50, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(50, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_31.setGeometry(QtCore.QRect(270, 60, 241, 31))
        self.lineEdit_31.setText("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(40, 240, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_29.setGeometry(QtCore.QRect(270, 240, 241, 31))
        self.lineEdit_29.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_17.setGeometry(QtCore.QRect(210, 300, 141, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(50, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 0, 1051, 661))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_32.setGeometry(QtCore.QRect(250, 70, 221, 31))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_18.setGeometry(QtCore.QRect(720, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setGeometry(QtCore.QRect(50, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setGeometry(QtCore.QRect(0, 160, 1011, 391))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 160, 1011, 481))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.label_43 = QtWidgets.QLabel(self.tab_9)
        self.label_43.setGeometry(QtCore.QRect(70, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_33.setGeometry(QtCore.QRect(260, 70, 221, 31))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_19.setGeometry(QtCore.QRect(730, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_44 = QtWidgets.QLabel(self.tab_10)
        self.label_44.setGeometry(QtCore.QRect(50, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_34.setGeometry(QtCore.QRect(260, 50, 221, 31))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_20.setGeometry(QtCore.QRect(730, 50, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 140, 1011, 391))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1061, 661))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setAutoFillBackground(True)
        self.tabWidget_4.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 1051, 581))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_29.setGeometry(QtCore.QRect(790, 590, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget_4.addTab(self.tab_11, "")
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(490, 130, 291, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_14.setGeometry(QtCore.QRect(330, 370, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(260, 130, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(490, 200, 291, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(260, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(490, 270, 291, 41))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(260, 280, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tabWidget_4.addTab(self.widget_2, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_16.setGeometry(QtCore.QRect(180, 60, 301, 31))
        self.lineEdit_16.setAutoFillBackground(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_29 = QtWidgets.QLabel(self.tab_12)
        self.label_29.setGeometry(QtCore.QRect(50, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_23.setGeometry(QtCore.QRect(560, 50, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setAutoFillBackground(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_17.setGeometry(QtCore.QRect(440, 280, 301, 31))
        self.lineEdit_17.setAutoFillBackground(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_30 = QtWidgets.QLabel(self.tab_12)
        self.label_30.setGeometry(QtCore.QRect(240, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_18.setGeometry(QtCore.QRect(440, 210, 301, 31))
        self.lineEdit_18.setAutoFillBackground(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_31 = QtWidgets.QLabel(self.tab_12)
        self.label_31.setGeometry(QtCore.QRect(240, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_19.setGeometry(QtCore.QRect(440, 350, 301, 31))
        self.lineEdit_19.setAutoFillBackground(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_32 = QtWidgets.QLabel(self.tab_12)
        self.label_32.setGeometry(QtCore.QRect(240, 350, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_16.setGeometry(QtCore.QRect(140, 510, 231, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_24.setGeometry(QtCore.QRect(620, 510, 241, 51))
        self.pushButton_24.setObjectName("pushButton_24")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tabWidget.addTab(self.tab_8, "")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(50, 290, 101, 91))
        self.pushButton_25.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/flat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_25.setIcon(icon5)
        self.pushButton_25.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_25.setObjectName("pushButton_25")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(980, -30, 411, 841))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("color:rgb(85, 85, 255);\n"
"background-color:rgb(0, 0, 0)\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(80, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_21.setGeometry(QtCore.QRect(50, 100, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("color: rgb(200, 130, 90);\n"
"background-color: rgb(0, 0, 127);\n"
"background-color: rgb(50, 50, 50);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_22.setGeometry(QtCore.QRect(50, 520, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("color: rgb(200, 130, 90);\n"
"background-color: rgb(50, 50, 50);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_27.setGeometry(QtCore.QRect(50, 240, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("color: rgb(200, 130, 90);\n"
"background-color: rgb(48, 47, 47);")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_28.setGeometry(QtCore.QRect(50, 380, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("color: rgb(200, 130, 90);\n"
"background-color: rgb(43, 43, 43);")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 380, 31, 81))
        self.pushButton_8.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 660, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("color: rgb(200, 130, 90);\n"
"\n"
"background-color: rgb(71, 71, 71);")
        self.pushButton_13.setObjectName("pushButton_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1353, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "ADD"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter book title"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Type</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Days</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Retrieve "))
        self.comboBox.setItemText(1, _translate("MainWindow", "Rent"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "15"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Enter client name"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "book_name"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "client_name"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "type"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "from"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "to"))
        self.pushButton_30.setText(_translate("MainWindow", "Export Day Operations To Excel Fiile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book code"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Title"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Description"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Book category"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Book Author"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Book Publisher"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Book Price"))
        self.pushButton_26.setText(_translate("MainWindow", "Export Books To Excel Fiile"))
        self.pushButton_31.setText(_translate("MainWindow", "count"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "All Books"))
        self.pushButton_7.setText(_translate("MainWindow", "SAVE"))
        self.label_3.setText(_translate("MainWindow", "Book title"))
        self.label_4.setText(_translate("MainWindow", "Book code "))
        self.label_5.setText(_translate("MainWindow", "Book price "))
        self.label_6.setText(_translate("MainWindow", "Category"))
        self.label_7.setText(_translate("MainWindow", "Publisher"))
        self.label_8.setText(_translate("MainWindow", "Author"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.widget), _translate("MainWindow", "Add New Book"))
        self.label_15.setText(_translate("MainWindow", "Book price "))
        self.label_16.setText(_translate("MainWindow", "Category"))
        self.label_17.setText(_translate("MainWindow", "Book title"))
        self.pushButton_9.setText(_translate("MainWindow", "SAVE"))
        self.label_18.setText(_translate("MainWindow", "Author"))
        self.label_19.setText(_translate("MainWindow", "Book code "))
        self.label_20.setText(_translate("MainWindow", "Publisher"))
        self.pushButton_10.setText(_translate("MainWindow", "SEARCH"))
        self.pushButton_11.setText(_translate("MainWindow", "DELETE"))
        self.label_21.setText(_translate("MainWindow", "Book title"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Edit or Delete book "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.groupBox.setTitle(_translate("MainWindow", "Add New User"))
        self.label_22.setText(_translate("MainWindow", "NAME"))
        self.label_23.setText(_translate("MainWindow", "EMAIL"))
        self.label_24.setText(_translate("MainWindow", "Password "))
        self.label_25.setText(_translate("MainWindow", "CONFIRM PASSWORD"))
        self.pushButton_12.setText(_translate("MainWindow", "ADD USER "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Edit user Information "))
        self.label_34.setText(_translate("MainWindow", "NAME"))
        self.label_35.setText(_translate("MainWindow", "Password "))
        self.pushButton_15.setText(_translate("MainWindow", "LOGIN"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Edit Your Data"))
        self.label_41.setText(_translate("MainWindow", "Password "))
        self.label_36.setText(_translate("MainWindow", "NAME"))
        self.label_39.setText(_translate("MainWindow", "CONFIRM PASSWORD"))
        self.pushButton_17.setText(_translate("MainWindow", "Edit User Data"))
        self.label_40.setText(_translate("MainWindow", "EMAIL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.pushButton_18.setText(_translate("MainWindow", "Add New Category"))
        self.label_42.setText(_translate("MainWindow", "New Category Name"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category name "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Categories  "))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Author name "))
        self.label_43.setText(_translate("MainWindow", "New Author Name"))
        self.pushButton_19.setText(_translate("MainWindow", "Add New Author"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Author"))
        self.label_44.setText(_translate("MainWindow", "New Publisher  Name"))
        self.pushButton_20.setText(_translate("MainWindow", "Add New Publisher "))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Publisher name "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Publisher "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Email"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Client ID"))
        self.pushButton_29.setText(_translate("MainWindow", "Export clients To Excel Fiile"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "All Clients"))
        self.pushButton_14.setText(_translate("MainWindow", "Add New Client"))
        self.label_10.setText(_translate("MainWindow", "Client Name"))
        self.label_11.setText(_translate("MainWindow", "Client Email"))
        self.label_12.setText(_translate("MainWindow", "Client ID"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.widget_2), _translate("MainWindow", "Add New Client"))
        self.label_29.setText(_translate("MainWindow", "client id"))
        self.pushButton_23.setText(_translate("MainWindow", "SEARCH"))
        self.label_30.setText(_translate("MainWindow", "Client Name"))
        self.label_31.setText(_translate("MainWindow", "Client_Email"))
        self.label_32.setText(_translate("MainWindow", "Client id"))
        self.pushButton_16.setText(_translate("MainWindow", "Delte_Client_data"))
        self.pushButton_24.setText(_translate("MainWindow", "Save_client_data"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Edit or Delete client"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Page"))
        self.label_45.setText(_translate("MainWindow", "Apply New Theme  ^_^"))
        self.pushButton_21.setText(_translate("MainWindow", "Dark_orange"))
        self.pushButton_22.setText(_translate("MainWindow", "Dark_grey"))
        self.pushButton_27.setText(_translate("MainWindow", "Dark"))
        self.pushButton_28.setText(_translate("MainWindow", "Dark_blue"))
        self.pushButton_8.setText(_translate("MainWindow", ">"))
        self.pushButton_13.setText(_translate("MainWindow", "Light"))
import icons_rc
